### PR TITLE
Add firefox support

### PR DESCRIPTION
**Pull request by j3soon**
Create firefox extension based on the original chrome extension.

### CODE REVIEW

**Comment by j3soon** [comment]
@swapagarwal Maybe this can be merged too?

**Comment by swapagarwal** [comment]
@j3soon Thanks for taking the time to work on this. I just installed it, and it works great based on my initial testing. 🎉 
Quick Question: I see that you have published this here: https://addons.mozilla.org/en-US/firefox/addon/mediumship/, Just wanted to make sure if you'll be willing to support maintaining it (bugs / feature requests)?

**Comment by j3soon** [comment]
Yes, it's my pleasure to maintain the firefox add on.

**Comment by j3soon** [comment]
@swapagarwal However, for problems like issue #4 is not yet fixable.

**Comment by swapagarwal** [comment]
Thanks @j3soon! 👍

**Pull request merged**
